#!/usr/bin/python
#
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
     # http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Annoys you more often depending on how many messages are in your inbox.

Reads from the ~/.annoymap folder to get usernames/OAuth tokens.

"""

import base64
import hmac
import imaplib
from optparse import OptionParser
import random
import sha
import smtplib
import sys
import time
import urllib
import yaml
import os
import glob
import pynotify
from datetime import datetime


def SetupOptionParser():
  # Usage message is the module's docstring.
  parser = OptionParser(usage=__doc__)
  parser.add_option('--every_minute_threshold',
                    default=30,
                    help='number of messages needed for notifications to show up every minute')
  parser.add_option('--generate_oauth_token',
                    action='store_true',
                    dest='generate_oauth_token',
                    help='generates an OAuth token and stores it to ~/.annoymap')
  parser.add_option('--imap_hostname',
                    default='imap.googlemail.com',
                    help='hostname of IMAP service')
  return parser


def UrlEscape(text):
  # See OAUTH 5.1 for a definition of which characters need to be escaped.
  return urllib.quote(text, safe='~-._')


def UrlUnescape(text):
  # See OAUTH 5.1 for a definition of which characters need to be escaped.
  return urllib.unquote(text)


def FormatUrlParams(params):
  """Formats parameters into a URL query string.

  Args:
    params: A key-value map.

  Returns:
    A URL query string version of the given parameters.
  """
  param_fragments = []
  for param in sorted(params.iteritems(), key=lambda x: x[0]):
    param_fragments.append('%s=%s' % (param[0], UrlEscape(param[1])))
  return '&'.join(param_fragments)


def EscapeAndJoin(elems):
  return '&'.join([UrlEscape(x) for x in elems])


def GenerateSignatureBaseString(method, request_url_base, params):
  """Generates an OAuth signature base string.

  Args:
    method: The HTTP request method, e.g. "GET".
    request_url_base: The base of the requested URL. For example, if the
      requested URL is
      "https://mail.google.com/mail/b/xxx@googlemail.com/imap/?" +
      "xoauth_requestor_id=xxx@googlemail.com", the request_url_base would be
      "https://mail.google.com/mail/b/xxx@googlemail.com/imap/".
    params: Key-value map of OAuth parameters, plus any parameters from the
      request URL.

  Returns:
    A signature base string prepared according to the OAuth Spec.
  """
  return EscapeAndJoin([method, request_url_base, FormatUrlParams(params)])


def GenerateHmacSha1Signature(text, key):
  digest = hmac.new(key, text, sha)
  return base64.b64encode(digest.digest())


def GenerateOauthSignature(base_string, consumer_secret, token_secret):
  key = EscapeAndJoin([consumer_secret, token_secret])
  return GenerateHmacSha1Signature(base_string, key)


def ParseUrlParamString(param_string):
  """Parses a URL parameter string into a key-value map.

  Args:
    param_string: A URL parameter string, e.g. "foo=bar&oof=baz".

  Returns:
    A key-value dict.
  """
  kv_pairs = param_string.split('&')
  params = {}
  for kv in kv_pairs:
    k, v = kv.split('=')
    params[k] = UrlUnescape(v)
  return params


class OAuthEntity(object):
  """Represents consumers and tokens in OAuth."""

  def __init__(self, key, secret):
    self.key = key
    self.secret = secret


def FillInCommonOauthParams(params, consumer, nonce=None, timestamp=None):
  """Fills in parameters that are common to all oauth requests.

  Args:
    params: Parameter map, which will be added to.
    consumer: An OAuthEntity representing the OAuth consumer.
    nonce: optional supplied nonce
    timestamp: optional supplied timestamp
  """
  params['oauth_consumer_key'] = consumer.key
  if nonce:
    params['oauth_nonce'] = nonce
  else:
    params['oauth_nonce'] = str(random.randrange(2**64 - 1))
  params['oauth_signature_method'] = 'HMAC-SHA1'
  params['oauth_version'] = '1.0'
  if timestamp:
    params['oauth_timestamp'] = timestamp
  else:
    params['oauth_timestamp'] = str(int(time.time()))


def GenerateRequestToken(consumer, scope, nonce, timestamp,
                         google_accounts_url_generator):
  """Generates an OAuth request token by talking to Google Accounts.

  Args:
    consumer: An OAuthEntity representing the OAuth consumer.
    scope: Scope for the OAuth access token.
    nonce: The nonce to use in the signature. If None is passed, a random nonce
      will be generated.
    timestamp: Timestamp to use in the signature. If None is passed, the current
      time will be used.
    google_accounts_url_generator: function that creates a Google Accounts URL
      for the given URL fragment.

  Returns:
    An OAuthEntity representing the request token.
  """
  params = {}
  FillInCommonOauthParams(params, consumer, nonce, timestamp)
  params['oauth_callback'] = 'oob'
  params['scope'] = scope
  request_url = google_accounts_url_generator.GetRequestTokenUrl()
  token = OAuthEntity(None, '')
  base_string = GenerateSignatureBaseString('GET', request_url, params)
  signature = GenerateOauthSignature(base_string, consumer.secret,
                                     token.secret)
  params['oauth_signature'] = signature

  url = '%s?%s' % (request_url, FormatUrlParams(params))
  response = urllib.urlopen(url).read()
  response_params = ParseUrlParamString(response)
  for param in response_params.items():
    print '%s: %s' % param
  token = OAuthEntity(response_params['oauth_token'],
                      response_params['oauth_token_secret'])
  print ('To authorize token, visit this url and follow the directions '
         'to generate a verification code:')
  print '  %s?oauth_token=%s' % (
      google_accounts_url_generator.GetAuthorizeTokenUrl(),
      UrlEscape(response_params['oauth_token']))
  return token


def GetAccessToken(consumer, request_token, oauth_verifier,
                   google_accounts_url_generator):
  """Obtains an OAuth access token from Google Accounts.

  Args:
    consumer: An OAuth entity representing the OAuth consumer.
    request_token: An OAuthEntity representing the request token (e.g. as
      returned by GenerateRequestToken.
    oauth_verifier: The verification string displayed to the user after
      completing Google Accounts authorization.
    google_accounts_url_generator: function that creates a Google Accounts URL
      for the given URL fragment.

  Returns:
    An OAuthEntity representing the OAuth access token.
  """
  params = {}
  FillInCommonOauthParams(params, consumer)
  params['oauth_token'] = request_token.key
  params['oauth_verifier'] = oauth_verifier
  request_url = google_accounts_url_generator.GetAccessTokenUrl()
  base_string = GenerateSignatureBaseString('GET', request_url, params)
  signature = GenerateOauthSignature(base_string, consumer.secret,
                                     request_token.secret)
  params['oauth_signature'] = signature

  url = '%s?%s' % (request_url, FormatUrlParams(params))
  response = urllib.urlopen(url).read()
  response_params = ParseUrlParamString(response)
  for param in ('oauth_token', 'oauth_token_secret'):
    print '%s: %s' % (param, response_params[param])
  return OAuthEntity(response_params['oauth_token'],
                     response_params['oauth_token_secret'])


def GenerateXOauthString(consumer, access_token, user, proto,
                         xoauth_requestor_id, nonce, timestamp):
  """Generates an IMAP XOAUTH authentication string.

  Args:
    consumer: An OAuthEntity representing the consumer.
    access_token: An OAuthEntity representing the access token.
    user: The Google Mail username (full email address)
    proto: "imap" or "smtp", for example.
    xoauth_requestor_id: xoauth_requestor_id URL parameter for 2-legged OAuth
    nonce: optional supplied nonce
    timestamp: optional supplied timestamp

  Returns:
    A string that can be passed as the argument to an IMAP
    "AUTHENTICATE XOAUTH" command after being base64-encoded.
  """
  method = 'GET'
  url_params = {}
  if xoauth_requestor_id:
    url_params['xoauth_requestor_id'] = xoauth_requestor_id
  oauth_params = {}
  FillInCommonOauthParams(oauth_params, consumer, nonce, timestamp)
  if access_token.key:
    oauth_params['oauth_token'] = access_token.key
  signed_params = oauth_params.copy()
  signed_params.update(url_params)
  request_url_base = (
      'https://mail.google.com/mail/b/%s/%s/' % (user, proto))
  base_string = GenerateSignatureBaseString(
      method,
      request_url_base,
      signed_params)
  #print 'signature base string:\n' + base_string + '\n'
  signature = GenerateOauthSignature(base_string, consumer.secret,
                                     access_token.secret)
  oauth_params['oauth_signature'] = signature

  formatted_params = []
  for k, v in sorted(oauth_params.iteritems()):
    formatted_params.append('%s="%s"' % (k, UrlEscape(v)))
  param_list = ','.join(formatted_params)
  if url_params:
    request_url = '%s?%s' % (request_url_base,
                             FormatUrlParams(url_params))
  else:
    request_url = request_url_base
  preencoded = '%s %s %s' % (method, request_url, param_list)
  #print 'xoauth string (before base64-encoding):\n' + preencoded + '\n'
  return preencoded


class GoogleAccountsUrlGenerator:
  def __init__(self, user):
    self.__apps_domain = None
    at_index = user.find('@')
    if at_index != -1 and (at_index + 1) < len(user):
      domain = user[(at_index + 1):].lower()
      if domain != 'gmail.com' and domain != 'googlemail.com':
        self.__apps_domain = domain

  def GetRequestTokenUrl(self):
    return 'https://www.google.com/accounts/OAuthGetRequestToken'

  def GetAuthorizeTokenUrl(self):
    if self.__apps_domain:
      return ('https://www.google.com/a/%s/OAuthAuthorizeToken' %
              self.__apps_domain)
    else:
      return 'https://www.google.com/accounts/OAuthAuthorizeToken'

  def GetAccessTokenUrl(self):
    return 'https://www.google.com/accounts/OAuthGetAccessToken'


def TestImapAuthentication(imap_hostname, user, xoauth_string):
  """Authenticates to IMAP with the given xoauth_string.

  Prints a debug trace of the attempted IMAP connection.

  Args:
    imap_hostname: Hostname or IP address of the IMAP service.
    user: The Google Mail username (full email address)
    xoauth_string: A valid XOAUTH string, as returned by GenerateXOauthString.
        Must not be base64-encoded, since IMAPLIB does its own base64-encoding.
  """
  print
  imap_conn = imaplib.IMAP4_SSL(imap_hostname)
  imap_conn.debug = 4
  imap_conn.authenticate('XOAUTH', lambda x: xoauth_string)
  imap_conn.select('INBOX')


def TestSmtpAuthentication(smtp_hostname, user, xoauth_string):
  """Authenticates to SMTP with the given xoauth_string.

  Args:
    smtp_hostname: Hostname or IP address of the SMTP service.
    user: The Google Mail username (full email address)
    xoauth_string: A valid XOAUTH string, as returned by GenerateXOauthString.
        Must not be base64-encoded, since IMAPLIB does its own base64-encoding.
  """
  smtp_conn = smtplib.SMTP(smtp_hostname, 587)
  smtp_conn.set_debuglevel(True)
  smtp_conn.ehlo('test')
  smtp_conn.starttls()
  smtp_conn.docmd('AUTH', 'XOAUTH ' + base64.b64encode(xoauth_string))


def main(argv):
  options_parser = SetupOptionParser()
  (options, args) = options_parser.parse_args()

  if not pynotify.init("icon-summary-body"):
    sys.exit(2)
  
  for filename in glob.glob(os.getenv('HOME') + '/.annoymap/*.annoy'):
    data = yaml.load(open(filename))
    oauth_token = data['oauth_token']
    oauth_token_secret = data['oauth_token_secret']
    user = data['user']

    consumer = OAuthEntity('anonymous', 'anonymous')
    google_accounts_url_generator = GoogleAccountsUrlGenerator(user)

    access_token = OAuthEntity(oauth_token, oauth_token_secret)
    xoauth_string = GenerateXOauthString(
        consumer, access_token, user, 'imap', None, None, None)
    conn = imaplib.IMAP4_SSL(options.imap_hostname)
    conn.authenticate('XoAUTH', lambda x: xoauth_string)

    count = conn.select('INBOX', True)[1][0]
    alert = ''
    for i in range((int(count) / 4) + 1):
      alert += str(count) + " messages in inbox for " + user  + "\n"

    # Figure out whether we should show a notification based on the threshold
    current_minute = datetime.now().minute
    if current_minute == 0:
      current_minute = 60
    factor = float(count) / float(options.every_minute_threshold)
    prev = int(factor * (current_minute - 1))
    curr = int(factor * (current_minute))
    if prev != curr:
      notification = pynotify.Notification('WHAT GIVES', alert)
      notification.show()

  if options.generate_oauth_token:
    request_token = GenerateRequestToken(consumer, 'https://mail.google.com', None,
                                         None,
                                         google_accounts_url_generator)
    oauth_verifier = raw_input('Enter verification code: ').strip()
    access_token = GetAccessToken(consumer, request_token, oauth_verifier,
                                  google_accounts_url_generator)

if __name__ == '__main__':
  main(sys.argv)
